### ISSUE TITLE
Outdated runtime

### ISSUE THREAD

**Issue by paluigi** [flathub/com.emqx.MQTTX#19] opened 2023-10-08 16:54 UTC
Hello, I get the following message when I update my flatpaks:

```
Info: org.freedesktop.Platform//21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Applications using this runtime:
   com.emqx.MQTTX
```
Is there any plan or timeline to update the runtime?
Thanks

**Comment by zachsmith** [comment] 2023-10-20 17:11
I opened https://github.com/flathub/com.emqx.MQTTX/pull/20 to address this. Feel free to test with `flatpak install --user https://dl.flathub.org/build-repo/57815/com.emqx.MQTTX.flatpakref`

**Comment by djfjeff** [comment] 2024-03-20 12:40
The issue is still present, is there any plan to ship an update soon to replace the outdated runtime? Thanks!

**Comment by razzeee** [comment] 2024-12-08 23:16
Should be fixed (in the next hours)

**Closed as completed** 2024-12-31 14:22 UTC
